---

- name: Deploy VM windows from template and customize
  vmware_guest:
    hostname: "{{ vc_hostname }}"
    username: "{{ vc_username }}"
    password: "{{ vc_password }}"
    validate_certs: no
    datacenter: "{{ vc_datacenter }}"
    folder: "{{ vc_folder }}"
    cluster: "{{ vc_cluster }}"
    name: "{{ item.vm_name }}"
    annotation: "{{ vc_note }}"
    state: poweredon
    disk:
    - size_gb: 20
      type: thin
      datastore: FORM01_R5_LUN75
    hardware:
       memory_mb: 4096
       num_cpus: 8
       scsi: paravirtual
    template: miquel-template-W2012R2-Std-ES
    networks:
    - name: VLAN6_Formacion
      ip: "{{ item.vm_ip }}"
      netmask: 255.255.255.0
      gateway: 192.168.6.1
   #   mac: 'aa:bb:dd:aa:00:14'
  #    domain: ncorafmacion.local
  #    dns_servers:
  #    - 192.168.6.100
  #    - 192.168.6.101
    customization:
      autologon: true
      dns_servers:
      - 192.168.6.100
      - 192.168.6.101
      dns_suffix: ncoraformacion.local
      domainadmin: administrador@ncoraformacion.local
      domainadminpassword: Secret123! 
      domain: ncoraformacion.local
      password: Secret321!
  #    runonce:
  #    - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\Enable-WinRM.ps1 -ForceNewSSLCert
  delegate_to: localhost
##
##Insert down the variables for each VM to deploy
##
  with_items:
    - { vm_name: x100, vm_ip: 10.0.0.100 }
    - { vm_name: x101, vm_ip: 10.0.0.101 }
    - { vm_name: x102, vm_ip: 10.0.0.102 }
    - { vm_name: x103, vm_ip: 10.0.0.103 }
    - { vm_name: x104, vm_ip: 10.0.0.104 }
    - { vm_name: x105, vm_ip: 10.0.0.105 }
